# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hit8.proto import servicio_pb2 as hit8_dot_proto_dot_servicio__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hit8/proto/servicio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MensajeriaCStub:
    """Servicio de comunicación entre nodos C (saludo bidireccional)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Saludar = channel.unary_unary(
                '/sdypp.hit8.MensajeriaC/Saludar',
                request_serializer=hit8_dot_proto_dot_servicio__pb2.MensajeSaludo.SerializeToString,
                response_deserializer=hit8_dot_proto_dot_servicio__pb2.MensajeRespuesta.FromString,
                _registered_method=True)


class MensajeriaCServicer:
    """Servicio de comunicación entre nodos C (saludo bidireccional)
    """

    def Saludar(self, request, context):
        """Envía un saludo a un nodo C y recibe la respuesta estructurada
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensajeriaCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Saludar': grpc.unary_unary_rpc_method_handler(
                    servicer.Saludar,
                    request_deserializer=hit8_dot_proto_dot_servicio__pb2.MensajeSaludo.FromString,
                    response_serializer=hit8_dot_proto_dot_servicio__pb2.MensajeRespuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdypp.hit8.MensajeriaC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdypp.hit8.MensajeriaC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MensajeriaC:
    """Servicio de comunicación entre nodos C (saludo bidireccional)
    """

    @staticmethod
    def Saludar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdypp.hit8.MensajeriaC/Saludar',
            hit8_dot_proto_dot_servicio__pb2.MensajeSaludo.SerializeToString,
            hit8_dot_proto_dot_servicio__pb2.MensajeRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RegistroDStub:
    """Servicio de directorio/registro del Nodo D (Registro y Consulta de nodos)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Registrar = channel.unary_unary(
                '/sdypp.hit8.RegistroD/Registrar',
                request_serializer=hit8_dot_proto_dot_servicio__pb2.RegistroSolicitud.SerializeToString,
                response_deserializer=hit8_dot_proto_dot_servicio__pb2.RegistroRespuesta.FromString,
                _registered_method=True)
        self.ConsultarActivos = channel.unary_unary(
                '/sdypp.hit8.RegistroD/ConsultarActivos',
                request_serializer=hit8_dot_proto_dot_servicio__pb2.ConsultaActivosSolicitud.SerializeToString,
                response_deserializer=hit8_dot_proto_dot_servicio__pb2.ConsultaActivosRespuesta.FromString,
                _registered_method=True)


class RegistroDServicer:
    """Servicio de directorio/registro del Nodo D (Registro y Consulta de nodos)
    """

    def Registrar(self, request, context):
        """Un nodo C se registra ante D indicando su IP y puerto gRPC, y recibe la lista de otros nodos C
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarActivos(self, request, context):
        """Consulta los nodos C activos en el sistema
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistroDServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Registrar': grpc.unary_unary_rpc_method_handler(
                    servicer.Registrar,
                    request_deserializer=hit8_dot_proto_dot_servicio__pb2.RegistroSolicitud.FromString,
                    response_serializer=hit8_dot_proto_dot_servicio__pb2.RegistroRespuesta.SerializeToString,
            ),
            'ConsultarActivos': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarActivos,
                    request_deserializer=hit8_dot_proto_dot_servicio__pb2.ConsultaActivosSolicitud.FromString,
                    response_serializer=hit8_dot_proto_dot_servicio__pb2.ConsultaActivosRespuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdypp.hit8.RegistroD', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdypp.hit8.RegistroD', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistroD:
    """Servicio de directorio/registro del Nodo D (Registro y Consulta de nodos)
    """

    @staticmethod
    def Registrar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdypp.hit8.RegistroD/Registrar',
            hit8_dot_proto_dot_servicio__pb2.RegistroSolicitud.SerializeToString,
            hit8_dot_proto_dot_servicio__pb2.RegistroRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarActivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdypp.hit8.RegistroD/ConsultarActivos',
            hit8_dot_proto_dot_servicio__pb2.ConsultaActivosSolicitud.SerializeToString,
            hit8_dot_proto_dot_servicio__pb2.ConsultaActivosRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
